- name: Chris Ostrouchov
  email: chris.ostrouchov@gmail.com
  num_commits: 15
  first_commit: 2020-05-12 18:44:08
  github: costrouc
- name: Anthony Scopatz
  email: scopatz@gmail.com
  num_commits: 55
  first_commit: 2020-06-13 13:54:48
- name: Chris Burr
  email: christopher.burr@cern.ch
  alternate_emails:
  - chrisburr@users.noreply.github.com
  num_commits: 5
  first_commit: 2020-09-23 08:12:24
  github: chrisburr
- name: Julian Rüth
  email: julian.rueth@fsfe.org
  num_commits: 1
  first_commit: 2020-09-24 18:10:18
  github: saraedum
- name: regro
  email: regro@users.noreply.github.com
  github: regro
  is_org: true
  num_commits: 0
  first_commit: 2020-11-09 21:39:07.908941
