- name: Chris Ostrouchov
  email: chris.ostrouchov@gmail.com
  num_commits: 13
  first_commit: 2020-05-12 18:44:08
- name: Anthony Scopatz
  email: scopatz@gmail.com
  num_commits: 51
  first_commit: 2020-06-13 13:54:48
